buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath "com.android.tools.build:gradle:8.9.0"
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
    mavenLocal()
    maven { url 'https://jitpack.io' }
  }
}

// Variables globales
ext {
  appName = 'OriginDex'
  projectVersion = '1.0'
  gdxVersion = '1.12.0'
}

configure(subprojects - project(':android')) {

  apply plugin: 'java'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }

  tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
  }
}
